config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :expenses, only: [:new, :create, :index] do
    collection do
      get 'expenses_with_friend/:friend_id', to: 'expenses#expenses_with_friend', as: 'expenses_with_friend'
      get 'expenses_due', to: 'expenses#expenses_due'
      get 'expenses_owe', to: 'expenses#expenses_owe'
    end

  end
  resources :settlements, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "expenses#index"
  get '/users', to: 'user#index'
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :description,:amount, presence: :true
  belongs_to :user
  has_many :expense_splits
  has_many :users,through: :expense_splits
  scope :shared_expenses_with_friend, ->(current_user_id, friend_id) {
    eager_load(:expense_splits)
      .where("(expenses.user_id = :current_user_id OR expenses.user_id = :friend_id)
            AND (expense_splits.user_id = :current_user_id OR expense_splits.user_id = :friend_id)",
             current_user_id: current_user_id, friend_id: friend_id)
  }
  scope :current_user_expenses, ->(current_user_id){
    eager_load(:expense_splits)
      .where("(expenses.user_id = :current_user_id)
            OR  (expense_splits.user_id = :current_user_id )",
             current_user_id: current_user_id)
  }
  scope :amount_due_to_current_user, ->(current_user_id){
    eager_load(:expense_splits)
      .where("expenses.user_id=:current_user_id AND expense_splits.paid_status = false",current_user_id: current_user_id).sum("expense_splits.amount")

  }
  scope :current_user_recovered_amount, ->(current_user_id){
    eager_load(:expense_splits)
      .where("expenses.user_id= :current_user_id AND expense_splits.paid_status = true",current_user_id: current_user_id)
      .sum("expense_splits.amount")
  }
  scope :expenses_due_to_current_user, ->(current_user_id){
    eager_load(:expense_splits)
      .where("expenses.user_id = :current_user_id",current_user_id: current_user_id)
  }

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense=Expense.new
  end

  def create

    @expense = Expense.create(expense_params.except(:user_ids))
    if @expense.save
      if params[:split_type] == 'equal'
        selected_user_ids = params[:expense][:user_ids].map(&:to_i) || params[:expense][:user_id].to_i
        total_amount = params[:expense][:amount].to_i
        split_amount = (total_amount.to_f / (selected_user_ids.length + 1)).round(2)
        selected_user_ids.each do |user_id|
          ExpenseSplit.create(expense_id: @expense.id, user_id: user_id, amount: split_amount) if user_id != @expense.user_id
        end
      elsif params[:split_type] == 'unequal'
        selected_user_ids = params[:expense][:user_ids].presence || params[:expense][:user_ids].to_i
        selected_user_ids = [selected_user_ids] unless selected_user_ids.is_a?(Array)
        selected_user_ids.each do |user_id|
          amount = params[:split_amount][user_id.to_s].to_f
          ExpenseSplit.create(expense_id: @expense.id, user_id: user_id, amount: amount) if user_id != @expense.user_id
        end
      end

      redirect_to expenses_path, notice: 'Expense created successfully.'
    else
       render :new, status: :unprocessable_entity
    end
  end


  def index
    @expenses=Expense.current_user_expenses(current_user.id)
    @amount_incurred=Expense.amount_due_to_current_user(current_user.id)
    @amount_owed=ExpenseSplit.amount_owe_to_current_user(current_user.id)
    @amount_recovered=Expense.current_user_recovered_amount(current_user.id)
  end

  def expenses_with_friend
    @friend=User.find(params[:friend_id])
    @friend_expenses=Expense.shared_expenses_with_friend(current_user.id,params[:friend_id])

  end

  def expenses_owe
    @expenses_owe=ExpenseSplit.expenses_owe_to_current_user(current_user.id)
  end

  def expenses_due
    @expenses_due=Expense.expenses_due_to_current_user(current_user.id)

  end

  private
  def expense_params
    params.require(:expense).permit(:description, :amount, :user_id,user_ids:[])

  end

end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
  <td><%= expense.description %></td>
  <td><%= expense.created_at.strftime('%m/%d/%Y') %></td>
  <td><%= expense.amount %></td>
  <td><%= expense_split.amount %></td>
  <td><%= expense_split.paid_status==false ? "Not Paid" : "Paid" %></td>

app/views/expenses/_form.html.erb
<%= form_with(model: @expense, local: true, class: "needs-validation", novalidate: true) do |form| %>
  <% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% @expense.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control", required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :amount, class: "form-label" %>
    <%= form.number_field :amount, class: "form-control", step: '0.01', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :paid_by, 'Paid By', class: "form-label" %>
    <%= form.collection_select :user_id, User.all, :id, :username, { prompt: "Select User" }, { class: "form-select", required: true } %>
  </div>

  <div class="mb-3">
    <label class="form-label">Split With:</label>
    <div class="form-check">
      <%= radio_button_tag 'split_type', 'equal', checked: true, class: "form-check-input" %>
      <%= label_tag 'equal', 'Equal Split', class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= radio_button_tag 'split_type', 'unequal', class: "form-check-input" %>
      <%= label_tag 'unequal', 'Unequal Split', class: "form-check-label" %>
    </div>
  </div>

  <div class="mb-3" id="users-select">
    <label class="form-label">Choose splitter (Don't pick payer) & enter split Amounts(for Unequal split).</label>
    <% User.all.each do |user| %>
      <div class="form-check">
        <%= check_box_tag 'expense[user_ids][]', user.id, false, class: "form-check-input", data: { "bs-target": "##{user.id}_validation" } %>
        <%= label_tag "split_amount[#{user.id}]", user.username, class: "form-check-label" %>
        <%= text_field_tag "split_amount[#{user.id}]", nil, placeholder: 'Split Amount', class: 'form-control split-amount', data: { "bs-target": "##{user.id}_validation" } %>
        <div id="<%= "#{user.id}_validation" %>" class="invalid-feedback">Please select a splitter and enter the split amount.</div>
      </div>
    <% end %>
  </div>



  <div class="mb-3">
    <%= form.submit "Submit", class: "btn btn-primary" %>
  </div>
 <%end %>

app/views/expenses/expenses_due.html.erb
<% if @expenses_due.present?  %>
  <br>
  <h1>Expenses you Due</h1>
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th>Description</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Divided amount</th>
      <th>Paid status</th>
      <th>Borrower</th>

    </tr>
    </thead>
    <tbody>
    <% @expenses_due.each do |expense| %>
      <% expense.expense_splits.each do |expense_split| %>
       <tr>
        <%=render 'expense',expense: expense,expense_split: expense_split,current_user: current_user %>
         <td><%= expense_split.user.username==current_user.username ? "You" : expense_split.user.username %></td>
         </td>
       </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>
<%else %>
  <h2> No Expenses</h2>
<%end %>
<%=link_to 'Back',expenses_path,class: "btn btn-primary" %>

app/views/expenses/expenses_owe.html.erb
<% if @expenses_owe.present?  %>
  <br>
  <h1>Expenses you owe</h1>
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th>Description</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Divided amount</th>
      <th>Paid status</th>
      <th>Paid by</th>

    </tr>
    </thead>
    <tbody>
    <tr>
    <% @expenses_owe.each do |expense_split| %>
      <%=render 'expense', expense: expense_split.expense,expense_split: expense_split,current_user: current_user%>
        <td><%= expense_split.expense.user.username==current_user.username ? "You" : expense_split.expense.user.username %></td>
        <td><%=link_to 'Settle',new_settlement_path(amount: expense_split.amount,expense_split_id: expense_split,user_id: current_user.id),class: "btn btn-primary" if (expense_split.user.username==current_user.username and expense_split.paid_status==false ) %></td>

        </tr>
    <% end %>
    </tbody>
  </table>
<%else %>
  <h2> No Expenses you owe</h2>
<%end %>
<%=link_to 'Back',expenses_path,class: "btn btn-primary" %>

app/views/expenses/expenses_with_friend.html.erb
<div>
  <br>
  <%if @friend_expenses.present? %>
    <h1>Expenses with <%=@friend.username %></h1>
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>Description</th>
        <th>Date</th>
        <th>Amount</th>
        <th>Divided amount</th>
        <th>Paid Status</th>
        <th>Paid By</th>
        <th>Borrower</th>

      </tr>
      </thead>
      <tbody>
      <% @friend_expenses.each do |expense| %>
        <% expense.expense_splits.each do |expense_split| %>
          <tr>
            <%=render 'expense',expense: expense,expense_split: expense_split,current_user: current_user %>
            <td><%= expense.user.username==current_user.username ? "You" : expense.user.username %></td>
            <td><%= expense_split.user.username==current_user.username ? "You" : expense_split.user.username %></td>
            <td><%=link_to 'Settle',new_settlement_path(amount: expense_split.amount,expense_split_id: expense_split,user_id: current_user.id),class: "btn btn-primary" if (expense_split.user.username==current_user.username and expense_split.paid_status==false ) %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>

<%else %>
    <div class="container-fluid">
      <%= "No Expenses with "+@friend.username %>
    </div>

    <%end %>
<div class="container-fluid"><br>
  <%=link_to 'Back',users_path,class: "btn btn-primary" %>
</div>

</div>

app/views/expenses/index.html.erb
<div class="container-fluid">
<% if @expenses.present?  %>
  <div class="container-fluid">
    <h2> Balance             : <%=@amount_incurred-@amount_owed %></h2>
    <h4> Money Spent   : <%=@amount_incurred %></h4>
    <h4> Amount Recovered : <%=@amount_recovered %></h4>
    <h4> Reimbursement :<%=@amount_owed %></h4>

  </div><br>

    <div class="container-fluid">
    <h1>Expenses</h1>
    <table class="table table-striped table-hover">
      <thead>
      <tr>
        <th>Description</th>
        <th>Date</th>
        <th>Amount</th>
        <th>Divided amount</th>
        <th>Paid Status</th>
        <th>Paid By</th>
        <th>Borrower</th>

      </tr>
      </thead>
      <tbody>
      <% @expenses.each do |expense| %>
        <% expense.expense_splits.each do |expense_split| %>
          <tr>
            <%=render 'expense',expense: expense,expense_split: expense_split,current_user: current_user %>
            <td><%= expense.user.username==current_user.username ? "You" : expense.user.username %></td>
            <td><%= expense_split.user.username==current_user.username ? "You" : expense_split.user.username %></td>
            <td><%=link_to 'Settle',new_settlement_path(amount: expense_split.amount,expense_split_id: expense_split,user_id: current_user.id) ,class: "btn btn-primary" if (expense_split.user.username==current_user.username and expense_split.paid_status==false ) %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

  <%else %>
    <div class="container-fluid">
      <h2> No Expenses Yet</h2>
    </div>

<%end %>


</div>

app/views/expenses/new.html.erb
<div>
  <h1>New Expense</h1>
  <div>
    <%=render 'form' %>
  </div>
</div>