config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :expenses, only: [:new, :create, :index] do
    collection do
      get 'expenses_with_friend/:friend_id', to: 'expenses#expenses_with_friend', as: 'expenses_with_friend'
      get 'expenses_due', to: 'expenses#expenses_due'
      get 'expenses_owe', to: 'expenses#expenses_owe'
    end

  end
  resources :settlements, only: [:new, :create]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "expenses#index"
  get '/users', to: 'user#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Splitwise</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" >SplitWise </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%=link_to "New Expense",new_expense_path,class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Expenses', expenses_path,class: "nav-link active", aria_current: 'page' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Friends', users_path,class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Expenses incurred',expenses_due_expenses_path,class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Owed Expenses', expenses_owe_expenses_path,class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path,class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%=button_to 'sign out',  destroy_user_session_path, form: { "data-turbo-confirm": "Are you sure?" },method: :delete ,class: "nav-link active" if current_user.present? %>
          </li>

        </ul>
        <div class="navbar-nav ms-auto">
          <li class="nav-item">
            <span class="nav-link active">Signed in as : <%= current_user.username if current_user.present?%></span>
          </li>
        </div>
      </div>
    </div>
  </nav>


<div class="container-fluid">
  <%= yield %>
</div>

  </body>
</html>